name: Communication Test

on:
  push:
    branches:
      - master

jobs:
  test_communication:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Runtime Image
        working-directory: ./ecal_runtime_container
        run: docker build . --rm -t ecal-runtime

      - name: Build Publisher Image for Test1
        working-directory: ./pub_container
        run: docker build --build-arg host_group_name=conti --rm -t publisher-image .

      - name: Build Subscriber Image for Test1
        working-directory: ./sub_container
        run: docker build --build-arg host_group_name=conti --rm -t subscriber-image .

      - name: Test Communication on same and different Hostname for same host_group_name
        run: |
          tests=(
            "host1"
            "host"
          )

          for test in "${tests[@]}"; do
            echo "Running test with hostname: $test"
            docker run --rm -d --name publisher-container --ipc=host --network=host --pid=host -h=host1 publisher-image
            docker run --rm -d --name subscriber-container --ipc=host --network=host --pid=host -h=$test subscriber-image
            sleep 3
            logs=$(docker logs subscriber-container)
            if [[ -n "$logs" ]]; then
              if [[ "$test" == "host1" ]]; then
                echo "Test passed: Messages received in logs"
              else
                echo "Test failed: Unexpected messages found in logs"
                exit 1
              fi
            else
              if [[ "$test" == "host1" ]]; then
                echo "Test failed: No messages found in logs"
                exit 1
              else
                echo "Test passed: No messages expected"
              fi
            fi
            docker stop publisher-container
            docker stop subscriber-container
          done

      - name: Prepare Publisher for Host-Group-Name-Test
        working-directory: ./pub_container
        run: docker build --build-arg host_group_name=continental --rm -t publisher-image .

      - name: Prepare Subscriber for Host-Group-Name-Test
        working-directory: ./sub_container
        run: docker build --build-arg host_group_name=conti --rm -t subscriber-image .

      - name: Test different Host-Group-Names
        run: |
          docker run --rm -d --name publisher-container --ipc=host --network=host --pid=host -h=host1 publisher-image
          docker run --rm  -d --name subscriber-container --ipc=host --network=host --pid=host -h=host1 subscriber-image
          sleep 3
          logs=$(docker logs subscriber-container)
          if [[ -n "$logs" ]]; then
            echo "Test1 passed: Messages received in logs"
          else
            echo "Test1 failed: No messages found in logs"
            exit 1
          fi