name: Communication Test

on:
  push:
    branches:
      - master

jobs:
  test_communication:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Runtime Image
        working-directory: ./ecal_runtime_container
        run: docker build . --rm -t ecal-runtime

      - name: Build Publisher Image
        working-directory: ./pub_container
        run: docker build --build-arg host_group_name=conti --rm -t publisher-image .

      - name: Build Subscriber Image
        working-directory: ./sub_container
        run: docker build --build-arg host_group_name=conti --rm -t subscriber-image .

      - name: Start Publisher Container
        run: docker run -d --name publisher-container --ipc=host --network=host --pid=host -h=host1 publisher-image

      - name: Start Subscriber Container
        run: docker run -d --name subscriber-container --ipc=host --network=host --pid=host -h=host1 subscriber-image

      - name: Wait before checking logs
        run: sleep 3

      - name: Test Communication
        run: |
          logs=$(docker logs subscriber-container)
          if [[ -n "$logs" ]]; then
            echo "Test1 passed: Messages received in logs"
          else
            echo "Test1 failed: No messages found in logs"
            exit 1
          fi

      - name: Stop Containers
        run: |
          docker stop publisher-container
          docker stop subscriber-container
