name: Communication Test

on:
  push:
    branches:
      - master

jobs:
  test_communication:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Runtime Image
        working-directory: ./ecal_runtime_container
        run: docker build . --rm -t ecal-runtime

      - name: Build Publisher Image for Test1
        working-directory: ./pub_container
        run: docker build --build-arg host_group_name=conti --rm -t publisher-image .

      - name: Build Subscriber Image for Test1
        working-directory: ./sub_container
        run: docker build --build-arg host_group_name=conti --rm -t subscriber-image .

      - name: Test1 Publisher- und Subscriber-Container with same Hostname
        run: |
          docker run --rm -d --name publisher-container --ipc=host --network=host --pid=host -h=host1 publisher-image
          docker run --rm  -d --name subscriber-container --ipc=host --network=host --pid=host -h=host1 subscriber-image
          sleep 3
          logs=$(docker logs subscriber-container)
          if [[ -n "$logs" ]]; then
            echo "Test1 passed: Messages received in logs"
            echo "Ping will be send"
            #docker run -d -it --name ecal-runtime --ipc=host --network=host --pid=host -h=host1 ecal-runtime
            #sleep 3
            #docker exec ecal-runtime ping -c 2 publisher-container
            #docker exec ecal-runtime ping -c 2 subscriber-container
          else
            echo "Test1 failed: No messages found in logs"
            exit 1
          fi
          

      - name: Stop Containers
        run: |
          docker stop publisher-container
          docker stop subscriber-container
          #docker stop ecal-runtime

      - name: Test2 Different Hostname
        run: |
          docker run --rm -d --name publisher-container --ipc=host --network=host --pid=host -h=host1 publisher-image
          docker run --rm  -d --name subscriber-container --ipc=host --network=host --pid=host -h=host subscriber-image
          sleep 3
          logs=$(docker logs subscriber-container)
          if [[ -n "$logs" ]]; then
            echo "Test2 failed: Communication was be able, but should not happen."
            exit 1
          else
            echo "Test1 passed: No Communication"
          fi

      - name: Stop Containers
        run: |
          docker stop publisher-container
          docker stop subscriber-container
